site_name: K8S homelab
repo_url: https://github.com/AndersBallegaard/homelab-k8s
site_url: https://homelab.anderstb.dk
site_author: Anders Ballegaard
site_description: "Documentation for my k8s based homelab"
theme:
  name: dracula
  hljs_languages:
    - yaml
    - bash
    - python
    - hcl
    - go

nav:
  - Home: index.md
  - Infrastructure:
    - Deployment:
      - Prepare admin node: infra/deployment/prepare_admin_node.md
      - Prepare proxmox: infra/deployment/prepare_proxmox.md
      - Setup cluster: infra/deployment/setup_cluster.md
    - Networking:
      - Overview: infra/networking/overview.md
      - VYOS Configuration: infra/networking/vyos.md
    - Conformance testing: infra/conformance_testing.md
    - FluxCD: infra/fluxcd.md
    - K8S: infra/kubernetes.md
    - Traefik: infra/traefik.md
  - Apps: apps/apps.md
  - Troubleshooting:
    - K8S Port forwarding: troubleshooting/port-forwarding.md
  - Information:
    - Documentation: info/docs.md