site_name: K8S homelab
repo_url: https://github.com/AndersBallegaard/homelab-k8s
site_url: https://andersballegaard.github.io/homelab-k8s/
site_author: Anders Ballegaard
site_description: "Documentation for my k8s based homelab"
theme:
  name: dracula
  hljs_languages:
    - yaml
    - bash
    - python
    - hcl
    - go

nav:
  - Home: index.md
  - Infrastructure: infra/infra.md
  - Apps: apps/apps.md
  - Troubleshooting: troubleshooting/troubleshooting.md
  - Information: info/info.md