site_name: Anders Ballegaard k8s homelab
repo_url: https://github.com/AndersBallegaard/homelab-k8s
site_url: https://docs.srv6.dk
site_author: Anders Ballegaard
site_description: "Documentation for my k8s based homelab"
features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.share
theme:
  name: null
  custom_dir: 'assets/cinder'
  colorscheme: dracula
  hljs_languages:
    - yaml
    - bash
    - python
    - hcl
    - go

nav:
  - Home: index.md
  - Infrastructure: 
    - infra/infra.md
  - Apps: 
    - apps/apps.md
  - Troubleshooting: 
    - troubleshooting/troubleshooting.md