apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
  - name: "instance-65500"
    localASN: 65500
    peers:
    - name: "r01"
      peerASN: 65666
      peerAddress: 2a0e:97c0:ae3:fff0::1
      peerConfigRef:
        name: "cilium-peer"
    - name: "r02"
      peerASN: 65666
      peerAddress: 2a0e:97c0:ae3:fff0::2
      peerConfigRef:
        name: "cilium-peer"
    
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
  namespace: kube-system
spec:
  authSecretRef: bgp-auth-secret
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
