---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: flux-system
stringData:
  values.yaml: |
    additionalArguments:
      - "--providers.kubernetescrd.allowCrossNamespace=true"
      - "--certificatesresolvers.letencrypt.acme.tlschallenge"
      - "--certificatesresolvers.letencrypt.acme.email=letsencrypt@srv6.dk"
      - "--certificatesresolvers.letencrypt.acme.storage=/data/acme.json"
      # Logging
      - --log.level=info
      - --log.format=json
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        helm.sh/resource-policy: keep
        meta.helm.sh/release-name: traefik
        meta.helm.sh/release-namespace: default
    ports:
      vault:
        port: 8200
        expose: true
        exposedPort: 8200
        protocol: TCP
    persistence:
      enabled: enable
      name: data
      accessMode: ReadWriteOnce
      size: 1024Mi
      path: /data
    podSecurityContext:
      fsGroup: null
    deployment: 
      initContainers:
        - name: fix-data-dir-permissions
          image: alpine:3.16.2
          command:
            - chown
            - -R  
            - 65532:65532
            - /data
          volumeMounts:
            - name: data
              mountPath: /data