apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor-ingress
  namespace: flux-system

spec:
  rules:
    - host: capacitor.k8s.srv6.dk
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  capacitor
                port:
                  number: 9000